select 
dt.LABEL_YYYY_MM_DD                 as DATE,
irf.RESOURCE_GROUP_COMBINATION_KEY  as GROUP_COMBINATION_KEY,
r.RESOURCE_NAME                     as RESOURCE_NAME,
mt.MEDIA_NAME                       as MEDIA_TYPE,
it.INTERACTION_TYPE                 as INTERACTION_TYPE,
max(irf.interaction_resource_id)    as IRF_ID,
sum(case when irf.CUSTOMER_HANDLE_COUNT > 0 then 1 else 0 end) as ACCEPTED,
sum(case when irf.CUSTOMER_HANDLE_COUNT = 0 and irf.CUSTOMER_RING_COUNT > 0 then 1 else 0 end) as NOTACCEPTED,
sum(case when irf.CUSTOMER_DIAL_COUNT + irf.CUSTOMER_RING_COUNT + irf.CUSTOMER_TALK_COUNT + irf.CUSTOMER_HANDLE_COUNT > 0 then 1 else 0 end) as OFFERED,
sum(irf.CUSTOMER_RING_COUNT + irf.CUSTOMER_DIAL_COUNT) as INVITE,
sum(irf.CUSTOMER_RING_DURATION + irf.CUSTOMER_DIAL_DURATION) as INVITE_TIME,
sum(irf.CUSTOMER_TALK_DURATION) as ENGAGE_TIME,
sum(irf.CUSTOMER_TALK_COUNT) as ENGAGE,
sum(irf.CONS_RCV_RING_DURATION) as Consult_Received_Invite_Time,
sum(case when irf.CUSTOMER_HANDLE_COUNT > 0 and irf.CONS_RCV_TALK_COUNT > 0 then irf.CONS_RCV_RING_DURATION else 0 end) as Consult_Received_Invite_Time_Accepted,
sum(case when mt.IS_ONLINE = 1 and irf.CUSTOMER_HANDLE_COUNT = 0 then irf.CONS_RCV_TALK_DURATION + irf.TALK_DURATION + irf.POST_CONS_XFER_TALK_DURATION + irf.CONF_JOIN_TALK_DURATION when mt.IS_ONLINE = 0 then irf.CONS_RCV_TALK_DURATION else 0 end) as CONSULT_RECEIVED_ENGAGE_TIME,
sum(case when mt.IS_ONLINE = 1 and irf.CUSTOMER_HANDLE_COUNT = 0 and irf.CONS_RCV_TALK_COUNT + irf.TALK_COUNT + irf.POST_CONS_XFER_TALK_COUNT + irf.CONF_JOIN_TALK_COUNT > 0 then 1 when mt.IS_ONLINE = 0 and it.INTERACTION_SUBTYPE_CODE <> 'INTERNALCOLLABORATIONREPLY' and irf.CONS_RCV_TALK_COUNT > 0 then 1 else 0 end) as CONSULT_RECEIVED_ACCEPTED,
sum(case when mt.IS_ONLINE = 1 and irf.CUSTOMER_HANDLE_COUNT = 0 and irf.CONS_RCV_TALK_COUNT + irf.TALK_COUNT + irf.POST_CONS_XFER_TALK_COUNT + irf.CONF_JOIN_TALK_COUNT > 0 then 1 when mt.IS_ONLINE = 0 and it.INTERACTION_SUBTYPE_CODE = 'INTERNALCOLLABORATIONREPLY' and irf.CONS_RCV_TALK_COUNT > 0 and td.TECHNICAL_RESULT_CODE <> 'COMPLETED' then 1 else 0 end) as CONSULT_RESPONSES,
sum(case when irf.CUSTOMER_HANDLE_COUNT > 0 and irf.CONS_RCV_TALK_COUNT > 0 then irf.CONS_RCV_TALK_DURATION else 0 end) as CONSULT_RCV_WARM_ENGAGE_TIME,
sum(case when irf.CUSTOMER_HANDLE_COUNT > 0 and irf.CONS_RCV_TALK_COUNT > 0 then 1 else 0 end) as CONSULT_RCV_ACC_WARM,
sum(case when ((mt.IS_ONLINE = 1 and td.TECHNICAL_RESULT_CODE not in ('TRANSFERRED' , 'CONFERENCED')) or (mt.IS_ONLINE = 0 and td.TECHNICAL_RESULT_CODE = 'TRANSFERRED')) and irf.CONS_INIT_TALK_COUNT + irf.CONS_INIT_HOLD_COUNT > 0 then 1 else 0 end) as CONSULT_INITIATED,
sum(case when (mt.IS_ONLINE = 1 and td.TECHNICAL_RESULT_CODE not in ('TRANSFERRED' , 'CONFERENCED')) or (mt.IS_ONLINE = 0 and td.TECHNICAL_RESULT_CODE = 'TRANSFERRED') then irf.CONS_INIT_TALK_DURATION + irf.CONS_INIT_HOLD_DURATION else 0 end) as CONSULT_INITIATED_TIME,
sum(case when irf.CUSTOMER_HANDLE_COUNT > 0 then irf.CONFERENCE_INITIATED_COUNT else 0 end) as CONFERENCE_INITIATED,
sum(case when irf.CUSTOMER_HANDLE_COUNT > 0 and irf.CONF_JOIN_TALK_COUNT + irf.CONF_JOIN_HOLD_COUNT > 0 then 1 else 0 end) as CONFERENCE_RECEIVED_ACCEPTED,
sum(case when irf.CUSTOMER_HANDLE_COUNT > 0 and td.TECHNICAL_RESULT_CODE= 'TRANSFERRED' then 1 else 0 end) as TRANSFER_INIT_AGENT,
sum(case when irf.CUSTOMER_HANDLE_COUNT > 0 and td.RESOURCE_ROLE_CODE= 'RECEIVEDTRANSFER' then 1 else 0 end) as XFER_RECEIVED_ACCEPTED,
sum(case when irf.STOP_ACTION = 1 and irf.CUSTOMER_HANDLE_COUNT > 0 then 1 else 0 end) as AGENT_DISCONNECT_FIRST
from INTERACTION_RESOURCE_FACT irf
inner join DATE_TIME  dt  on(irf.START_DATE_TIME_KEY = dt.DATE_TIME_KEY)
inner join TECHNICAL_DESCRIPTOR  td  on(irf.TECHNICAL_DESCRIPTOR_KEY = td.TECHNICAL_DESCRIPTOR_KEY)
inner join Resource_ r on (r.resource_key = irf.resource_key)
left outer join ANCHOR_FLAGS  af  on(irf.ANCHOR_FLAGS_KEY = af.ANCHOR_FLAGS_KEY)
inner join MEDIA_TYPE  mt  on(mt.MEDIA_TYPE_KEY = irf.MEDIA_TYPE_KEY)
inner join INTERACTION_TYPE  it  on(it.INTERACTION_TYPE_KEY = irf.INTERACTION_TYPE_KEY)
where (dt.cal_date between CURRENT_DATE - 2 and CURRENT_DATE - 1) and (irf.RESOURCE_KEY in (select r_.RESOURCE_KEY from RESOURCE_ r_ where r_.RESOURCE_TYPE_CODE not in ('ROUTINGPOINT' , 'QUEUE')) and not (irf.CONS_RCV_RING_DURATION > 0 and irf.CONS_RCV_TALK_COUNT + irf.CUSTOMER_RING_COUNT = 0) and not (irf.CUSTOMER_RING_COUNT = 0 and irf.RING_COUNT > 0 and irf.TALK_COUNT = 0) and not (irf.CONS_INIT_DIAL_COUNT > 0 and irf.CONS_INIT_TALK_COUNT = 0) and not (it.INTERACTION_SUBTYPE_CODE = 'INTERNALCOLLABORATIONREPLY' and irf.CONS_RCV_TALK_DURATION = 0) and not (td.TECHNICAL_RESULT_CODE= 'DEFERRED' and td.RESULT_REASON_CODE= 'CALLBACKACCEPTED')
)
group by dt.LABEL_YYYY_MM_DD, irf.RESOURCE_GROUP_COMBINATION_KEY, r.resource_name, irf.TENANT_KEY, mt.MEDIA_NAME, it.INTERACTION_TYPE
