select 
    smsf.TENANT_KEY 		AS TENANT_KEY,
	max(ten.TENANT_NAME) 	AS TENANT_NAME,
	smsf.MEDIA_TYPE_KEY 	AS MEDIA_TYPE_KEY,
	max(mt.MEDIA_NAME)		AS MEDIA_NAME,
	r_.AGENT_NAME 			AS AGENT_NAME,
	smsf.START_TS_TIME 		AS START_TS_TIME,
	smsf.END_TS_TIME 		AS END_TS_TIME,
	smsf.ACTIVE_FLAG 		AS ACTIVE_FLAG,
	smsf.RESOURCE_GROUP_COMBINATION_KEY 	AS GROUP_COMBINATION_KEY,
	smsf.START_DATE_TIME_KEY 				AS DATE_TIME_KEY,
	smsf.SM_RES_SESSION_FACT_KEY 			AS CUST_COL_8,
	sum(smsf.TOTAL_DURATION) 				AS WJXBFS1
from	SM_RES_SESSION_FACT_GI2	smsf
	join	(SELECT RESOURCE_GI2.* FROM RESOURCE_GI2 WHERE RESOURCE_TYPE_CODE='AGENT' AND RESOURCE_SUBTYPE='Agent')	r_
	  on 	(smsf.RESOURCE_KEY = r_.RESOURCE_KEY)
	join	MEDIA_TYPE	mt
	  on 	(smsf.MEDIA_TYPE_KEY = mt.MEDIA_TYPE_KEY)
	join	TENANT	ten
	  on 	(smsf.TENANT_KEY = ten.TENANT_KEY)
where	
smsf.START_DATE_TIME_KEY BETWEEN ( SELECT RANGE_START_KEY FROM RELATIVE_RANGE WHERE RANGE_NAME='Yesterday') 
AND 
(SELECT RANGE_END_KEY-1 FROM RELATIVE_RANGE WHERE RANGE_NAME='Yesterday')

group by	
	smsf.TENANT_KEY,
	smsf.MEDIA_TYPE_KEY,
	r_.AGENT_NAME,
	smsf.START_TS_TIME,
	smsf.END_TS_TIME,
	smsf.ACTIVE_FLAG,
	smsf.RESOURCE_GROUP_COMBINATION_KEY,
	smsf.START_DATE_TIME_KEY,
	smsf.SM_RES_SESSION_FACT_KEY