SELECT   
DT.LABEL_YYYY_MM_DD  as Day,  
SSF.INTERACTION_ID   as INTERACTION_ID,
SSF.SESSION_ID       as SESSION_ID, 
SSF.ANI              as ANI,
max(case when SUMF.SEQUENCE_ID = 1  then SDRM.MILESTONE ELSE NULL END) as Milestone_1,
max(case when SUMF.SEQUENCE_ID = 2  then SDRM.MILESTONE ELSE NULL END) as Milestone_2,
max(case when SUMF.SEQUENCE_ID = 3  then SDRM.MILESTONE ELSE NULL END) as Milestone_3,
max(case when SUMF.SEQUENCE_ID = 4  then SDRM.MILESTONE ELSE NULL END) as Milestone_4,
max(case when SUMF.SEQUENCE_ID = 5  then SDRM.MILESTONE ELSE NULL END) as Milestone_5,
max(case when SUMF.SEQUENCE_ID = 6  then SDRM.MILESTONE ELSE NULL END) as Milestone_6,
max(case when SUMF.SEQUENCE_ID = 7  then SDRM.MILESTONE ELSE NULL END) as Milestone_7,
max(case when SUMF.SEQUENCE_ID = 8  then SDRM.MILESTONE ELSE NULL END) as Milestone_8,
max(case when SUMF.SEQUENCE_ID = 9  then SDRM.MILESTONE ELSE NULL END) as Milestone_9,
max(case when SUMF.SEQUENCE_ID = 10 then SDRM.MILESTONE ELSE NULL END) as Milestone_10,
max(case when SUMF.SEQUENCE_ID = 11 then SDRM.MILESTONE ELSE NULL END) as Milestone_11,
max(case when SUMF.SEQUENCE_ID = 12 then SDRM.MILESTONE ELSE NULL END) as Milestone_12,
max(case when SUMF.SEQUENCE_ID = 13 then SDRM.MILESTONE ELSE NULL END) as Milestone_13,
max(case when SUMF.SEQUENCE_ID = 14 then SDRM.MILESTONE ELSE NULL END) as Milestone_14,
max(case when SUMF.SEQUENCE_ID = 15 then SDRM.MILESTONE ELSE NULL END) as Milestone_15,
max(case when SUMF.SEQUENCE_ID = 16 then SDRM.MILESTONE ELSE NULL END) as Milestone_16,
max(case when SUMF.SEQUENCE_ID = 17 then SDRM.MILESTONE ELSE NULL END) as Milestone_17,
max(case when SUMF.SEQUENCE_ID = 18 then SDRM.MILESTONE ELSE NULL END) as Milestone_18,
max(case when SUMF.SEQUENCE_ID = 19 then SDRM.MILESTONE ELSE NULL END) as Milestone_19,
max(case when SUMF.SEQUENCE_ID = 20 then SDRM.MILESTONE ELSE NULL END) as Milestone_20

FROM SDR_SESSION_FACT SSF 
	INNER JOIN DATE_TIME DT                  ON (SSF.START_DATE_TIME_KEY = DT.DATE_TIME_KEY)
	INNER JOIN SDR_USER_MILESTONE_FACT SUMF  ON (SSF.SESSION_ID = SUMF.SESSION_ID)
	INNER JOIN SDR_MILESTONE SDRM            ON (SDRM.ID = SUMF.SDR_MILESTONE_KEY)

WHERE DT.cal_date >= CURRENT_DATE

GROUP BY 
DT.LABEL_YYYY_MM_DD,
SSF.INTERACTION_ID,
SSF.SESSION_ID,
SSF.ANI

ORDER BY 1

