SELECT   
IXN.INTERACTION_ID,  
IXN.MEDIA_SERVER_IXN_GUID, 
R_.RESOURCE_NAME,
ixn.start_ts as I_STARTTIME,
IXN.END_TS as I_ENDTIME,
IRF.START_TS as R_START_TIME,
IRF.END_TS as R_END_TIME,
IRF.TALK_DURATION
from INTERACTION_FACT IXN
INNER JOIN INTERACTION_RESOURCE_FACT IRF on IXN.INTERACTION_ID = IRF.INTERACTION_ID
INNER JOIN DATE_TIME DT on DT.DATE_TIME_KEY = IRF.START_DATE_TIME_KEY
INNER JOIN RESOURCE_ R_ on IRF.RESOURCE_KEY = R_.RESOURCE_KEY
WHERE DT.LABEL_YYYY_MM_DD = '2021-11-19' and
R_.RESOURCE_SUBTYPE = 'Agent'   
and irf.TALK_DURATION > 15 
-- and IRF.TALK_COUNT !=0
and IRF.MEDIA_TYPE_KEY =1 -- 'Voice'